module.exports = {
  content: [
    "./index.html",           
    "./src/**/*.{js,ts,jsx,tsx}",  
  ],
  theme: {
    extend: {
      colors: {
        "main-bg": "#fdf6ec",
        "main-font": "#4a3f35",
        "sub-1": "#999999",
        "sub-2": "#777777",
        "custom-brown": "#7e6d61",
        "btn-bg": "#fcefe9",
        "btn-text": "#5a4231",
        "btn-hover": "#f5e1d5",
        "icon-bg": "#f3f0e8",
        "icon-bg-hover": "#e1d7c3",
        "nav-text": "#333333",
        "card-border": "#e5e5e5",
        "api-card-border": "#ccc",
        "apply-btn-bg": "#ff6b6b",
        "modal-close-text": "#666",
        "modal-close-hover-text": "#ff4444",
        "quote-border": "#a3c7db",
        "quote-text": "#d8b08c",
        "quote-cite": "#808080",
        "search-bg": "#f1f1f1",
        "focus-blue": "#007bff",
        "placeholder-text": "#888",
        "contact-h3": "#222",
        "contact-text": "#444",
        "contact-link": "#0077cc",
        "contact-link-hover": "#005da0",
        "input-shadow": "#e0dcd2",
        "input-focus-bg": "#fffef8",
      },
      fontFamily: {
        "nanum-myeongjo": ['"Nanum Myeongjo"', "serif"],
        pretendard: ['"Pretendard"', "sans-serif"],
      },
    },
  },
  plugins: [],
};
